site_name: The Ryo Programming Language
site_url: https://ryolang.org
site_description: A statically typed programming language with a focus on simplicity and ease of use.
theme:
  name: material
  logo: assets/ryo.svg
  favicon: assets/ryo.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
repo_url: https://github.com/ryolang/ryo
repo_name: ryo
site_author: artefactop
plugins:
  - search
extra:
  homepage: https://ryolang.org
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences